#' fastqc
#'
#' @description
#' This function is a wrapper of the software FASTQC.
#'
#' @param project_path Path to the project folder.
#' @param fastqc_dir Path to fastqc directory.
#' @param pattern File extension. Default to \code{fastq}.
#'
#' @details
#' The function \code{fastqc} uses the program fastqc to do some quality control checks.
#' The fastqc program is available at \url{https://www.bioinformatics.babraham.ac.uk/projects/fastqc/}.
#'
#' @returns
#' The function \code{fastqc} returns quality control files generated by the
#' program fastqc in the `reports` folder.
#'
#' @export


fastqc <- function(project_path = NULL,
                   fastqc_dir = NULL,
                   pattern = "fastq"){

  # get the current working directory
  current_wd <- getwd()

  # get the file list of demultiplexed files
  file_list <- list.files(file.path(project_path, "1_demultiplexed"),
                          full.names = TRUE,
                          pattern = pattern)

  # set the directory to fastqc
  setwd(fastqc_dir)

  # run fastqc with system and the move the created files to a folder to another
  for(i in 1:length(file_list)){
    cmd <- paste("java -Xmx250m -classpath .;./sam-1.103.jar;./jbzip2-0.9.jar uk.ac.babraham.FastQC.FastQCApplication",
                 file_list[i])

    system(cmd)

    html_file <- list.files(file.path(project_path, "1_demultiplexed"), pattern = "html", full.names = FALSE)

    file.rename(from = file.path(project_path, "1_demultiplexed", html_file),
                to = file.path(project_path, "reports", html_file))

    zip_file <- list.files(file.path(project_path, "1_demultiplexed"), pattern = "zip", full.names = FALSE)

    file.rename(from = file.path(project_path, "1_demultiplexed", zip_file),
                to = file.path(project_path, "reports", zip_file))

  }

  # restore the original working directory
  setwd(current_wd)
}
