#' fastqc
#'
#' @description
#' This function is a wrapper of the software FASTQC.
#'
#' @param project_path Path to the project folder.
#' @param fastqc_dir Path to fastqc directory.
#' @param pattern File extension. Default to \code{fastq}.
#'
#' @details
#' The function \code{fastqc} uses the program fastqc to do some quality control checks.
#' The fastqc program is available at \url{https://www.bioinformatics.babraham.ac.uk/projects/fastqc/}.
#' This function requires Java and FastQC to be installed and accessible.
#' Java must be available on the system PATH.
#'
#' @returns
#' The function \code{fastqc} returns quality control files generated by the
#' program fastqc in the `reports` folder.
#' 
#' @importFrom tools file_path_sans_ext
#'
#' @export


fastqc <- function(project_path = NULL,
                   fastqc_dir = NULL,
                   pattern = "fastq"){
  
  # check if java is installed
  java <- Sys.which("java")
  if (java == "") {
    stop("Java not found. Please install Java and ensure it is on the system PATH.")
  }

  # set the reports directory for later usage
  reports_dir <- file.path(project_path, "reports")
  
  # get the file list of demultiplexed files
  file_list <- list.files(file.path(project_path, "1_demultiplexed"),
                          full.names = TRUE,
                          pattern = pattern)
  
  # build OS-correct classpath
  sep <- .Platform$path.sep
  cp <- paste(c(".", "sam-1.103.jar", "jbzip2-0.9.jar"), collapse = sep)

  # make directories changes sage
  old_wd <- getwd()
  on.exit(setwd(old_wd), add = TRUE)
  setwd(fastqc_dir)

  # run fastqc with system and the move the created files to a folder to another
  for (f in file_list) {
    # run fastqc via java
    args <- c(
      "-Xmx250m",
      "-classpath", cp,
      "uk.ac.babraham.FastQC.FastQCApplication",
      f
    )
    system2("java", args = args)
    
    # move only files matching this input's base name
    base <- tools::file_path_sans_ext(basename(f))
    out_html <- file.path(project_path, "1_demultiplexed", paste0(base, "_fastqc.html"))
    out_zip  <- file.path(project_path, "1_demultiplexed", paste0(base, "_fastqc.zip"))
    
    if (file.exists(out_html)) file.rename(out_html, file.path(reports_dir, basename(out_html)))
    if (file.exists(out_zip))  file.rename(out_zip,  file.path(reports_dir, basename(out_zip)))
  }
  
  invisible(NULL)
}
