#' open multiqc report
#'
#' @description
#' This function open the report generated by multiqc
#'
#' @param project_path Path to the project folder.
#'
#' @export
#'
#' @importFrom utils browseURL

open_multiqc <- function(project_path = NULL){

  # open the html from R
  utils::browseURL(paste0('file://', file.path(project_path, "reports", "multiqc_report.html")))
}
